version: '3.8'

services:
  skoda-leasing-overview:
    build: .
    container_name: skoda-overview
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
